index.js, package-lock.json, package.json, readme.md
Npm setup, install express and nodemon.
Create basic express server.
Add basic folders structure.
=> MS-00: Npm and express setup

controllers/admins.js, data/admins.json, index.js
Added endpoints and functions to list all the admins and a specific one.
Added mock data for admins.
Added JSON formatting to the server.
=> MS-02: Admins - List admins

controllers/sessions.js, data/sessions.json, index.js
Task: 
- MS27- Sessions - Create Session
Commit history:
- Create sessions.js
-  Add mock data for sessions
- Add endpoint to create session
- Fix endpoint to create session
- Add json formatting
- Add function to create session
- Add module exports for create
- Fix identation
Questions: 
- Do the commits describe well the construction of the code?
- Should I refer to a file when I write a commit? For example: "Fix identation in index"
=> MS-27: Sessions - Create session

controllers/positions.js, index.js
Add "create" controller in position.js
Add create position endpoint in index.js
=> MS-23: Positions - Create positions

controllers/sessions.js, index.js
Task:
- update session 
Commit history :
- Add endpoint to update session
-  Add function to update session
- Add if stament to return message when id can't be changind in update function
- Add message when id not found in update function
- Add message when id not found in update function
- Add update to module exports
- Fix code identation
=> MS-28: Sessions - Update Session

controllers/positions.js, index.js
Add "update" controller in position.js
Add update position endpoint in index.js
*I renamed this branch because a mistake and I had to create this new PR. I also closed the previous one *
=> MS-24: Positions - Update position

controllers/profiles.js, data/profiles.json, index.js, package-lock.json
Fix PR corrections and merge with latest Develop
=> MS-15: Profiles - Create Profile

controllers/admins.js, index.js
Create endpoint and function to update admin.
=> MS-01: Admin - Update admin

controllers/positions.js, index.js
Add remove positions controllers positions.js.
Add remove position  endpoint in index.js
Fix exceptions control in the others controllers.
=> MS-25: Positions - remove positions

controllers/sessions.js, index.js
Task:
- List sessions
Extra: 
- List a session by id
- List sessions by psychologist
Commit history:
- Add endpoint to list sessions
- Add endpoint to list a session by id
- Add function to list sessions
- Add function to list a session by id
- Add getAll & GetById to module exports
- Add function to list sessions by psychologist
-  Add getByIdPsychologist to module exports
- Add endpoint to list sessions by psychologist
=> MS-30: Sessions - List Session

controllers/psychologists.js, index.js
**Commits**
- MS-09: add function in psychologist.js to remove psychologists
- MS-09: add changes in index.js to remove psychologists
=> MS-09: Psychologist - Remove Psychologists

controllers/clients.js, index.js
=> MS-12: update client

controllers/psychologists.js, index.js
**Commits**
- MS-10: add the getAll command to lists all the psychologists
- MS-10: add the getById command to get by the ID of the psychologists
- MS-10: add the getByName command to lists by the name of the psychologysts 
- MS-10: add changes in index.js to lists the psychologists
=> MS-10: Psychologist - List Psychologists

controllers/applications.js, data/applications.json, index.js
Create mock data (thanks @nicolasblasco )
Create applications controllers.
Add endpoints in index.js.
=> MS-31: Applications - all features

index.js
Fix index.js by adding deleted controllers from pull request #31
=> Fix Index.js

controllers/profiles.js
Correct tab indentations
Add return errors and remove "Else"
*This refactor was made before a change of plans, this Ticket now belongs to @ValentinaCollareta
=> MS-39: Profiles - Refactor

controllers/clients.js
Refactored clients code:
- Added HTML codes to responses.
- Added error responses.
- Added parameters validation on create method.
- Rewrote update method assingments using OR operator.
- Rewrote if statements that could be writen in one line
- Removed else statements. Use return instead.
- Removed trailing spaces.
- Removed unnecessary parenthesis and semicolons.
=> MS-35: Clients - Refactor

controllers/psychologists.js, data/psychologists.json
Added HTTP codes to responses.
Added parameters validation on create method.
Removed else statements. Use return instead.
Removed trailing spaces.
=> MS-34: Psychologists refactor

controllers/positions.js, data/positions.json
-  Fix indentation to 2 spaces for positions.js & positions.json 
- Add HTTP request status codes to response messages in all functions
- Change IF statment to OR statment in update function
=> MS-41: Positions refactor

controllers/applications.js
=> MS-37: Applications refactor

controllers/interviews.js, data/interviews.json
**Commits**
- MS-38: Fix indentation in interviews.js & interviews.json files
- MS-38: add return and some brackets to the functions
- MS-38: fix the module.exports by deleting the repeated properties
=> MS-38: Interviews Refactor

.eslintrc.json, package.json
=> [FIX] - MS-43: Add semicolons at the end of each line and remove husky from production deps

src/models/applications.js
=> [FIX] - MS-46: Update applications model

src/controllers/candidates.js
- Add HTTP status
- Add return statement instead of else
- Remove blank spaces
- Remove unnecessary comments
- Add validations
- Fix update for education and work experience
Note: for simplicity we're momentarily using the position in the array to select which education or work experience info to modify. This will be refactored in the API Rest update.
=> [FIX] - MS-40: Candidates refactor

collections/Psychologists.postman_collection.json, src/controllers/psychologists.js, src/models/psychologists.js, src/routes/index.js, src/routes/psychologists.js, src/validations/psychologists.js
- Add psychologists model 
- Add endpoints, middlewares and controllers using GET, POST, PUT & DELETE
- Import Postman collection
=> MS-47: Psychologists api rest

collections/Profile.postman_collection.json, src/controllers/profiles.js, src/models/profiles.js, src/routes/index.js, src/routes/profiles.js, src/validations/profiles.js
* Add new model
* Add endpoints + controllers using GET, POST, PUT & DELETE
* Import Postman collection
=> MS-51: profiles-api-rest

collections/Candidates.postman_collection.json, src/controllers/candidates.js, src/index.js, src/models/candidates.js, src/routes/candidates.js, src/routes/index.js, src/validations/candidates.js, src/validations/validations.js
- Create model for candidates
- Create endpoints to get, create, update and delete candidates
- Create postman collection
- Add validations for the data sent
=> MS-44: Candidates - API Rest

collections/Interviews.postman_collection.json, package-lock.json, src/controllers/interviews.js, src/models/interviews.js, src/routes/index.js, src/routes/interviews.js, src/validations/interviews.js
**COMMITS**
- MS-50: add and set up the interviews.js file in models folder
- MS-50: edit functions in the controllers folder interviews.js file
- MS-50: add all the functions to the interviews.js file in controller´… 
- MS-50: add routes to the controllers
- MS-50: add the interviews.postman_collection.json file in collections… 
- MS-50: pritier interviews.js file in models folder
=>  MS-50: Interviews - api rest

public/layout.html
* Use fieldset to wrap each group of label, input & error div
* Change that error div for error span
=> [FIX] MS-53: layout

src/routes/interviews.js, src/validations/interviews.js
BUG: 
- The function "require" was used as a validation function. This function is reserved for another purpose.  
Solution:
- Change function name "require" to "required" in both interviews validations and interviews routes
=> [FIX] MS-50: Interviews - API Rest

public/css/styles.css, public/layout.html
* Change fieldset style in styles.css
* Change Errors msg id in layout.html
=> [FIX] MS-53: fix layout style details

public/index.html, src/index.js, src/routes/index.js
- add express static  in index.js
- add /api/endpoints routes.
=> MS: add express static and /api/endpoints

src/index.js
=> [FIX] - MS-66: Clean up old routes in index.js

collections/Candidates.postman_collection.json, src/controllers/candidates.js, src/routes/candidates.js, src/routes/interviews.js, src/validations/interviews.js
- Add endpoints to update and delete education and work experience
- Refactor add more information function
=> [FEATURE] - MS-63: Candidates - Education and Work experience endpoints

.husky/pre-commit
=> [FIX] - Remove git add . from husky rule

public/admins.html, public/css/adminsStyles.css, public/js/admins.js, public/js/validations4Admins.js, public/validations/admins.js
**Commits**
- MS-54: test commit 
- MS-54: add function to fetch all the admins in DB
- MS-54: change the way to close the modal by add or remove a class
- MS-54: function update fixed
- MS-54: function Update done
- MS-54: add validations for admins Name
- MS-54: add validation for admins email
- MS-54: add validations for admins username
- MS-54: add validations for admins password
- MS-54: modify the html and css to make superadmin a select tag instea… 
- MS-54: add the hide class to validations submit button
- MS-54: ready to revision
=> MS-54: Admins CRUD

public/css/profiles.css, public/js/profiles.js, public/profiles.html, public/validations/profiles.js, src/validations/profiles.js
**Commits**
- MS-60: test commit
- MS-60: create html layout and a table with the profiles documents
- MS-60: create the modal and add the function to get all the profiles … 
- MS-60: add DELETE function
- MS-60: add Create and Update Function
- MS-60: fix the routes to deploy in heroku
- MS-60: modified title in modal to show edit or create
- MS-60: add validations folder and a validation for the profile name
- MS:60: add validation for the profile description
- MS-60: problem with create and update fixed
- MS-60: create a modal warning for delete in html and styles in css
- MS-60: add function delete to the modal warning
=> MS-60: Profiles CRUD

readme.md
=> MS-68: Add more documentation to readme

public/js/profiles.js
=> [FIX] MS-60: Profiles CRUD

public/js/admins.js
=> [FIX]MS-54: Admins CRUD

public/css/styles.css, public/js/sessions.js
- Change url from localhost:4000 to `window.location.origin`
- Add missing styles.css
=> [FIX] - MS-62: Sessions crud

public/js/clients.js
=> [FIX]MS-57: Clients CRUD

readme.md
=> FEATURE: Update readme

readme.md
=> [FEATURE] - Update readme titles
